language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - git clone https://github.com/zenovich/runkit.git runkit
  - cd runkit
  - phpize
  - ./configure
  - make
  - sudo make install
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - cd ..
script: phpunit --coverage-text .